#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

# Che-Theia workflow
# matrix jobs with alpine and ubi8
name: CI

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout che-theia source code
    - name: build
      run: |
        echo ${FOOBAR} > /tmp/mysecret
        cat /tmp/mysecret
      env:
        FOOBAR: ${{ secrets.FOOBAR }}
